$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $projectRoot

$docker = Get-Command docker -ErrorAction SilentlyContinue
if (-not $docker) {
  throw "Docker Desktop is required for the local PostgreSQL/Supabase database. Install and start Docker Desktop, then run pnpm db:local:setup again."
}

& $docker.Source info *> $null
if ($LASTEXITCODE -ne 0) {
  throw "Docker Desktop is installed but not running. Start it, then run pnpm db:local:setup again."
}

$pnpm = Get-Command pnpm.cmd -ErrorAction SilentlyContinue
if (-not $pnpm) {
  throw "pnpm.cmd was not found. Install pnpm 9 or newer first."
}

& $pnpm.Source exec supabase start
if ($LASTEXITCODE -ne 0) {
  throw "The local Supabase stack failed to start."
}

$statusLines = & $pnpm.Source exec supabase status -o env
if ($LASTEXITCODE -ne 0) {
  throw "Unable to read the local Supabase connection details."
}

$status = @{}
foreach ($line in $statusLines) {
  if ($line -match '^([A-Z0-9_]+)=(.*)$') {
    $value = $Matches[2].Trim()
    if ($value.Length -ge 2 -and $value.StartsWith('"') -and $value.EndsWith('"')) {
      $value = $value.Substring(1, $value.Length - 2)
    }
    $status[$Matches[1]] = $value
  }
}

$apiUrl = $status["API_URL"]
$databaseUrl = $status["DB_URL"]
$serviceRoleKey = $status["SERVICE_ROLE_KEY"]
if (-not $apiUrl -or -not $databaseUrl -or -not $serviceRoleKey) {
  throw "Supabase status did not return API_URL, DB_URL, and SERVICE_ROLE_KEY."
}

function New-LocalSecret {
  $bytes = New-Object byte[] 48
  $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $generator.GetBytes($bytes)
  } finally {
    $generator.Dispose()
  }
  return [Convert]::ToBase64String($bytes).Replace("+", "-").Replace("/", "_").TrimEnd("=")
}

$envPath = Join-Path $projectRoot ".env.local"
$adminSecret = New-LocalSecret
$sessionSecret = New-LocalSecret

$content = @(
  "# Local-only configuration generated by pnpm db:local:setup",
  "APP_ENVIRONMENT=local",
  "SUPABASE_URL=$apiUrl",
  "SUPABASE_SERVICE_ROLE_KEY=$serviceRoleKey",
  "DATABASE_URL=$databaseUrl",
  "ADMIN_SETUP_SECRET=$adminSecret",
  "SESSION_SECRET=$sessionSecret",
  "APP_ORIGIN=http://127.0.0.1:5000"
)

Set-Content -LiteralPath $envPath -Value $content -Encoding UTF8

Write-Output "Local database is ready."
Write-Output "Application API: $apiUrl"
Write-Output "Supabase Studio: http://127.0.0.1:54323"
Write-Output "Navicat PostgreSQL: host=127.0.0.1 port=54322 database=postgres user=postgres password=postgres"
Write-Output "Local application settings were written to .env.local."
